{
 "title": "PVE Summary Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Identity",
    "label": "Identity",
    "query": {
     "query": "label_values(pve_cluster_status,identify)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_status{is_now=\"true\", identify=\"$Identity\"}",
     "legendFormat": "{{identify}}"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_status{is_now=\"true\", identify=\"$Identity\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_time_metrics_generate{identify=\"$Identity\"}",
     "legendFormat": "{{identify}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"uptime\", identify=\"$Identity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web UI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label{identify=\"$Identity\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"model\", identify=\"$Identity\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "PVE Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"pveversion\", identify=\"$Identity\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"cpus\", identify=\"$Identity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"sockets\", identify=\"$Identity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Quorum",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "pve_cluster_status{is_now=\"false\", identify=\"$Identity\"}"
    }
   ]
  },
  {
   "title": "CPU - Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"cpu\", identify=\"$Identity\"}",
     "legendFormat": "{{identify}}"
    }
   ]
  },
  {
   "title": "Memory - Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"memorytotal\", identify=\"$Identity\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "pve_cluster_label_status_node{label=\"memoryused\", identify=\"$Identity\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pve_cluster_label_status_node{label=\"memoryfree\", identify=\"$Identity\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap - Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_cluster_label_status_node{label=\"swaptotal\", identify=\"$Identity\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "pve_cluster_label_status_node{label=\"swapused\", identify=\"$Identity\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pve_cluster_label_status_node{label=\"swapfree\", identify=\"$Identity\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pve_cluster_label_graph_node{label=\"cpu\", identify=\"$Identity\"}",
       "legendFormat": "{{identify}}"
      }
     ]
    },
    {
     "title": "Memory - Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pve_cluster_label_graph_node{label=\"memtotal\", identify=\"$Identity\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "pve_cluster_label_graph_node{label=\"memused\", identify=\"$Identity\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "pve_cluster_label_graph_node{label=\"memfree\", identify=\"$Identity\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Swap - Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pve_cluster_label_graph_node{label=\"swaptotal\", identify=\"$Identity\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "pve_cluster_label_graph_node{label=\"swapused\", identify=\"$Identity\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "pve_cluster_label_graph_node{label=\"swapfree\", identify=\"$Identity\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Network - Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "pve_cluster_label_graph_node{label=\"netin\", identify=\"$Identity\"}",
       "legendFormat": "{{label}}"
      },
      {
       "expr": "pve_cluster_label_graph_node{label=\"netout\", identify=\"$Identity\"}",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  }
 ]
}